### ISSUE TITLE
Editor wont lunch

### ISSUE THREAD

**Issue by daalfa** [CodeSpacePlus/Blasphemous_Save_Editor#2]
Whenever I run it throws this:

```
Error at line 2 of Initializing Blasphemous Save Editor process.
JSONToVariant function called.
Invalid JSON format

----- Technical information -----

Project : Blasphemous Save Editor

WL call:
Process of 'Initializing Blasphemous Save Editor', line 2
'JSONToVariant' function, syntax 0

What happened?
Invalid JSON format

Error code: 40129
Level: fatal error

Dump of the error of 'wd240xml.dll' module (24.0.110.0).
Debugging information:
Fonction (0,325)
Additional information:
EIT_PILEWL :
Initializing Blasphemous Save Editor (), line 2
EIT_DATEHEURE : 14/06/2021 22:11:40
EIT_TYPE_WDFILE : <4097>
EIT_IDCODE : <196608>
```

**Comment by CodeSpacePlus** [comment]
I'll have to try it out myself. Unfortunately, I don't have the tools to debug the application. Best case scenario it could be something wrong with the JSON you're trying to read.

**Comment by CodeSpacePlus** [comment]
Okay! I found the probable issue. Before running the .exe make sure to extract all the contents of Assets.rar into a folder along with the .exe this should fix the problem.

**Comment by ReaperF0X** [comment]
![image](https://github.com/CodeSpacePlus/Blasphemous_Save_Editor/assets/151860067/c758f18d-604f-4eee-8c3f-3e269a142beb)

Error at line 2 of Initializing Blasphemous Save Editor process.
JSONToVariant function called.
Invalid JSON format

----- Technical information -----

Project : Blasphemous Save Editor

WL call:
Process of 'Initializing Blasphemous Save Editor', line 2
'JSONToVariant' function, syntax 0

What happened?
Invalid JSON format

Error code: 40129
Level: fatal error

Dump of the error of 'wd240xml.dll' module (24.0.110.0).
Debugging information:
Fonction (0,325)
Additional information:
EIT_PILEWL :
Initializing Blasphemous Save Editor (), line 2
EIT_DATEHEURE : 03/05/2024 20:12:59
EIT_TYPE_WDFILE : <4097>
EIT_IDCODE : <196608>
