### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by ReaperF0X** [CodeSpacePlus/Blasphemous_Save_Editor#6]
Error at line 2 of Initializing Blasphemous Save Editor process.
JSONToVariant function called.
Invalid JSON format

----- Technical information -----

Project : Blasphemous Save Editor

WL call:
Process of 'Initializing Blasphemous Save Editor', line 2
'JSONToVariant' function, syntax 0

What happened?
Invalid JSON format

Error code: 40129
Level: fatal error

Dump of the error of 'wd240xml.dll' module (24.0.110.0).
Debugging information:
Fonction (0,325)
Additional information:
EIT_PILEWL :
Initializing Blasphemous Save Editor (), line 2
EIT_DATEHEURE : 03/05/2024 20:12:59
EIT_TYPE_WDFILE : <4097>
EIT_IDCODE : <196608>

**Comment by CodeSpacePlus** [comment]
Make sure to extract the assets.rar contents, they should be in the same folder where the Blasphemous_Save_Editor.exe is located
![Screenshot 2024-05-03 113123](https://github.com/CodeSpacePlus/Blasphemous_Save_Editor/assets/15057145/5d05c8d7-0caa-4038-87f2-a036cec5bd04)

**Comment by ReaperF0X** [comment]
Ah thank you, your screenshot shows me that the .exe should have been in the asset file.
