### ISSUE TITLE
Error by WLanguage security mechanism while open the exe

### ISSUE THREAD

**Issue by Pyryte** [CodeSpacePlus/Blasphemous_Save_Editor#8]
Error at line 2 of Initializing Blasphemous Save Editor process.
JSONToVariant function called.
Invalid JSON format

----- Technical information -----

Project : Blasphemous Save Editor

WL call:
Process of 'Initializing Blasphemous Save Editor', line 2
'JSONToVariant' function, syntax 0

What happened?
Invalid JSON format

Error code: 40129
Level: fatal error

Dump of the error of 'wd240xml.dll' module (24.0.110.0).
Debugging information:
Fonction (0,325)
Additional information:
EIT_PILEWL :
Initializing Blasphemous Save Editor (), line 2
EIT_DATEHEURE : 18/05/2024 22:14:48
EIT_TYPE_WDFILE : <4097>
EIT_IDCODE : <196608>

Help

**Comment by CodeSpacePlus** [comment]
https://github.com/CodeSpacePlus/Blasphemous_Save_Editor/issues/6#issuecomment-2093550593
